### ISSUE TITLE
Collection performance

### ISSUE THREAD

**Issue by ThomasBuchinger** [sapcc/vrops-exporter#71]
Hi,
I setup the exporter in our fairly small environment (15 Hosts, 300 VMs), but when I call the exporter, the request takes very long to return the data.

As I understand the code, you are doing one query per metric. Therefore the size of the environment should not matter (at least as far the exporter code is concerned). I suspect that either the number of API call from the exporter is causing the issue, or VROPS itself is really slow.

Do you see the same behavior? Any Ideas how to improve performance?

### Observed result
* When the exporter has been running for a while (I am currently in inventory iteration 60) a single collection run takes about 8 minutes
* The time it for a single collection varies widely, I have seen everything from 5 minutes up to 13 minutes
* It seems to be a bit faster when the exporter just startet: approx 1-3 minutes. The times slowly creeps up the longer the exporter runs
* A single API call (/auth/token/aquire) takes 0.2 seconds (over the same proxy)
* The query endpoint responds in 200ms too (though I did not manage to craft a query that actually returns data)
* As expected the VmStatsCollector takes by far the most time, followed by HostStatsCollector
* If I drop VmStatsCollector, the time drops to initially 5 seconds, but still slows down to 25 seconds (iteration 9)

### Test setup:
I run the exporter on a development server and access the VROPS API over a proxy. I trigger the collect via curl from the same machine.
I tried it on my laptop (same proxy, but an additional VPN) with the same result
```bash
export USER=username
export PASSWORD=password
export PORT=8080
export https_proxy="http://proxy.local:8080"
export http_proxy="http://proxy.local:8080"
export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
export DEBUG=1

./bin/python exporter.py --atlas atlas.json --collector ClusterStatsCollector --collector ClusterPropertiesCollector --collector HostSystemPropertiesCollector --collector HostSystemStatsCollector --collector SampleCollector --collector DatastoreStatsCollector --collector VMStatsCollector --collector VMPropertiesCollector
```

**Comment by viennaa** [comment]
Hi Thomas,

good analysis, helpful to see how it works in other environments. Let me just comment on a few things you figured:

* We have spent the last weeks to improve overall stability first, since there were couple things not working very well. As a side effect, performance increased a lot. Make sure you have the latest code.
* The biggest collection painpoint is VMs indeed, that's why we often did exclude these while developing. We increased the sleep time in the InventoryBuilder to only build the Inventory once every 30mins. This at least decreases the api load, because we have hit the normal limit already
```

WARN server.config.ThrottleFilter - IP address 10.46.14.156 has reached the max concurrent requests allowed of 50
``` 
It wasn't only, due to the inventory collection, but also through some prometheus config. Moreover, I'd recommend using service discovery to only scrape in a 10minute interval. Scrapes every minute are overkill. Furthermore we increased concurrent requests to 100, which is fine as of VMware.
* There is a branch, which introduced some threading in the inventory collection you can try out. Technically it should be working, but haven't really pursued that since it is _just_ inventory and the main work is in the collectors apparently: https://github.com/sapcc/vrops-exporter/tree/threading_inventory (there might be concurrency issues in there)
* Just a number from one of our environments: >300 hosts and > 19000 VMs do finish a run in a little more than 3 minutes, which is acceptable for me (all collectors enabled).

**Comment by ThomasBuchinger** [comment]
I think I found the problem: Everytime the  Collector reads the UUIDs from the inventory endpoint, it appends all the UUIDs to the existing list and never clears it. Therefore the query gets longer with every run.

**Comment by viennaa** [comment]
We introduced a versioning of the inventory already. Moreover, inventory is now a dedicated server to be run in another pod. Only thing increasing currently is memory usage in the main container (exporter.py). Tends to work good until roughly 500MB. That's why we introduced this as a resource limit meanwhile.

With the inventory still being in place it also just loses one scrape max (the one when it is getting killed) and can resume straight away.

Simple usage is: 
* get the current iteration
* query inventory with this iteration .../datastores/90

**Comment by ThomasBuchinger** [comment]
My version is 2 weeks old, but in already had the iterated inventory. The problems is the Collector remembers the UUIDs from the last scratch and appends the UUIDs from the inventory

**Comment by viennaa** [comment]
That sounds like the leak I was looking for. Can you elaborate where exactly?

**Comment by ThomasBuchinger** [comment]
https://github.com/sapcc/vrops-exporter/blob/master/BaseCollector.py#L112

```python
def get_hosts_by_target(self):
        if not hasattr(self, 'target_hosts'):
            self.target_hosts = dict()
        host_dict = self.get_hosts()
        for uuid in host_dict:
            host = host_dict[uuid]
            if host['target'] not in self.target_hosts:
                self.target_hosts[host['target']] = list()
            # Check if the uuid is already in the list
            if uuid not in self.target_hosts[host['target']]:
                self.target_hosts[host['target']].append(uuid)
        return self.target_hosts
```
I tested it with an check if the UUID is already in the list, however you probably want to reset the whole list for every scrap in case the host disappears from the inventory

Also this code is pretty dense and repeated over and over for every type of object, therefore I was planning to refactor the code and make the object-type a parameter to a `get_resource_by_target(resource_name)`
